### ISSUE TITLE
What changed from 1 to 2?

### ISSUE THREAD

**Issue by Alex0007** [soyuka/relieve#1]
This snippet of code worked on 1.0.3 and stopped working on v2 (findAvailableWorker returns CallableTask instance) worker.get('result') returns Promise

What breaking changes are made from 1.0.3 to 2.0.0?

``` js
let parse = item => Rx.Observable
  .just(1)
  .do(() => console.log('parse', item))
  .flatMap(() => findAvailableWorker())
  .do(worker => worker.call('parse', item))
  .flatMap(worker => worker.get('result'))
```

**Comment by soyuka** [comment]
My bad I didn't release the fix, 2.0.0 is broken due to a small mistake please update to 2.0.1.

https://github.com/soyuka/relieve/commit/bc175394c40c02efaed9d640e12ea1c1733be763

Breaking change was to use rest parameters ([ok with node 6](http://node.green/)) in functions and use more arrow functions so node 4 and 5 aren't supported with 2.0. Previously, node 4 and 5 where supported engines.
